#Trying to set up travis ci
sudo: required

services:
  - docker

language: java
dist: trusty

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

env:
  - DOCKER_IMAGE=ghajduk3/mejnik-scooters:latest

script:
  - mvn clean package -U
  - docker build -t "$DOCKER_IMAGE" .


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE"