apiVersion: apps/v1
kind: Deployment
metadata:
  name: mejnik-scooters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mejnik-scooters
  template:
    metadata:
      labels:
        app: mejnik-scooters
    spec:
      containers:
        - image: mejnik.azurecr.io/mejnik-scooters:v1
          name: mejnik-scooters
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: mejnik-scooters
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: server
  selector:
    app: mejnik-scooters